### ISSUE TITLE
Doesn't populate PHP DocBlocks Unless Syntax is set to 'Plain Text'

### ISSUE THREAD

**Issue by magiclantern** [spadgos/sublime-jsdocs#278]
Hi,

I am running Sublime Text 3 (3059) on OS X 10.9.2.

I've tried this with both the version on Package Control as well as cloning directly from here.

The plugin works as expected for JavaScript, however the PHP docblock will not populate if the syntax is set to 'PHP.' If it's set to 'Plain Text,' everything works as expected.

Result of logging commands in ST is the same in both cases, though, it's `command: jsdocs`.

Any ideas on how this could be fixed?

Thanks so much

**Comment by mahakaal** [comment]
Having the same problem here, when I try to have a function documentated just when I finish to type /** the folowing lines are highlighted in red and can't press enter on the comment line, unless i delete the /**. Works for JS and plain text.

**Comment by spadgos** [comment]
Everything seems normal on my machine. Can you see if there's any errors in the console? Do you have a small example file which exhibits the error?

**Comment by mahakaal** [comment]
In the console thsi is the error I get
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "jsdocs in C:\Users\manu\AppData\Roaming\Sublime Text 3\Installed Packages\DocBlockr.sublime-package", line 163, in run
  File "jsdocs in C:\Users\manu\AppData\Roaming\Sublime Text 3\Installed Packages\DocBlockr.sublime-package", line 358, in parse
  File "jsdocs in C:\Users\manu\AppData\Roaming\Sublime Text 3\Installed Packages\DocBlockr.sublime-package", line 426, in formatFunction
  File "jsdocs in C:\Users\manu\AppData\Roaming\Sublime Text 3\Installed Packages\DocBlockr.sublime-package", line 501, in parseArgs
  File "jsdocs in C:\Users\manu\AppData\Roaming\Sublime Text 3\Installed Packages\DocBlockr.sublime-package", line 509, in getArgInfo
  File "jsdocs in C:\Users\manu\AppData\Roaming\Sublime Text 3\Installed Packages\DocBlockr.sublime-package", line 812, in getArgName
AttributeError: 'NoneType' object has no attribute 'group'

and this is the screenshot of the moment
![error](https://cloud.githubusercontent.com/assets/726449/7437267/5ed06aac-f056-11e4-9d98-e0c850bd1af8.PNG)

**Comment by spadgos** [comment]
You have a syntax error there: the variables need to start with a `$`

```php
function newFunction ($a, $b) { .. }
```

**Comment by mahakaal** [comment]
That's embarassing, sorry I completely forgot about them, was working with other language and completly forgot about basics syntax. Thanks, for the reply, for the other things, this plugin is just mind blowing.

**Comment by spadgos** [comment]
No worries!
