### ISSUE TITLE
Problem with /**[enter or tab]

### ISSUE THREAD

**Issue by patrickelectric** [spadgos/sublime-jsdocs#300]
/*\* [Enter or Tab]
void sendControldatain(float rpy[3],float drpy[3],float position[3],float velocity[3])
{
  headSerialResponse(48, MSP_CONTROLDATAIN);
  for (int i = 0; i < 3; ++i)
    serializeFloat(rpy[i]);
  for (int i = 0; i < 3; ++i)
    serializeFloat(drpy[i]);
  for (int i = 0; i < 3; ++i)
    serializeFloat(position[i]);
  for (int i = 0; i < 3; ++i)
    serializeFloat(velocity[i]);
  tailSerialReply();
}

the console show:
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "jsdocs in /home/patrick/.config/sublime-text-3/Installed Packages/DocBlockr.sublime-package", line 91, in run
  File "jsdocs in /home/patrick/.config/sublime-text-3/Installed Packages/DocBlockr.sublime-package", line 286, in parse
  File "jsdocs in /home/patrick/.config/sublime-text-3/Installed Packages/DocBlockr.sublime-package", line 354, in formatFunction
  File "jsdocs in /home/patrick/.config/sublime-text-3/Installed Packages/DocBlockr.sublime-package", line 764, in parseArgs
  File "jsdocs in /home/patrick/.config/sublime-text-3/Installed Packages/DocBlockr.sublime-package", line 469, in parseArgs
  File "jsdocs in /home/patrick/.config/sublime-text-3/Installed Packages/DocBlockr.sublime-package", line 770, in getArgName
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by thelfensdrfer** [comment]
Same error for me.
