### ISSUE TITLE
Refuses to parse php __construct

### ISSUE THREAD

**Issue by designermonkey** [spadgos/sublime-jsdocs#342]
Here's the console error message

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "jsdocs in /Users/designermonkey/Library/Application Support/Sublime Text 3/Installed Packages/DocBlockr.sublime-package", line 148, in run
  File "jsdocs in /Users/designermonkey/Library/Application Support/Sublime Text 3/Installed Packages/DocBlockr.sublime-package", line 343, in parse
  File "jsdocs in /Users/designermonkey/Library/Application Support/Sublime Text 3/Installed Packages/DocBlockr.sublime-package", line 411, in formatFunction
  File "jsdocs in /Users/designermonkey/Library/Application Support/Sublime Text 3/Installed Packages/DocBlockr.sublime-package", line 486, in parseArgs
  File "jsdocs in /Users/designermonkey/Library/Application Support/Sublime Text 3/Installed Packages/DocBlockr.sublime-package", line 494, in getArgInfo
  File "jsdocs in /Users/designermonkey/Library/Application Support/Sublime Text 3/Installed Packages/DocBlockr.sublime-package", line 783, in getArgType
TypeError: Can't convert 'NoneType' object to str implicitly
```

Hope this helps.

**Comment by spadgos** [comment]
This is working for me:

```php
<?php
class BaseClass {
   /**
    * [__construct description]
    */
   function __construct() {}
}
```

Could you include the code which is failing?

**Comment by gerardroche** [comment]
I can't reproduce this either. Can you show the code snippet and steps to reproduce?

**Comment by designermonkey** [comment]
It happens intermittently, it works for so long, and then one day, won't work. As soon as it happens again, I'll definitely provide feedback.

**Comment by designermonkey** [comment]
Aha! I've got it!

Using new PHP syntax for arrays causes it.

```php
public function something(array $arr = [])
```

It happens in any function, not just construct.

**Comment by gerardroche** [comment]
https://github.com/spadgos/sublime-jsdocs/pull/373 fixes this.

**Comment by designermonkey** [comment]
Is that released yet? Thanks.

**Comment by gerardroche** [comment]
@designermonkey No, not yet.

**Comment by gerardroche** [comment]
@designermonkey this has been released. Can you confirm that it fixes the issue?

**Comment by designermonkey** [comment]
Certainly does!

Thanks very much.
