### ISSUE TITLE
"jsdoc_decorate" keybinding not working on OSX

### ISSUE THREAD

**Issue by erikfox** [spadgos/sublime-jsdocs#360]
There doesn't seem to be a bind conflict for `ctrl+enter`, but the command doesn't execute. Just returns to new line.

Tried setting binding in package to `ctrl+return`, `command+enter`, `super+enter`, etc. Still did not work.

**Comment by spadgos** [comment]
Can you enable command logging? <kbd>Ctrl+~</kbd> to open the console and input `sublime.log_commands(True)`, then try the keyboard combo. If it doesn't show `jsdocs_decorate`, it might be due to the recent addition of a flag to disable that feature. The key combo will only fire if the setting is set to `true`, which should be the default.

**Comment by mattcoker** [comment]
This is the only output I got when hitting `<Ctrl+Enter>`:
`command: insert {"characters": "\n"}`

I was able to get it working with the following text in my Sublime Text-->Preferences-->Package Settings-->DocBlocker-->Settings User:

    {
        "jsdocs_decorate": true,
    }

**Comment by mrchess** [comment]
Same issue on Sublime 2, 2.0.2. @mattcoker's fix suggestion worked -- directly adding the setting to config.

**Comment by Matoo125** [comment]
Hello, not sure if it should work, but I have this error
```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Sublime Text 3\sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "jsdocs in C:\Users\Matej\AppData\Roaming\Sublime Text 3\Installed Packages\DocBlockr.sublime-package", line 1346, in run
AttributeError: 'NoneType' object has no attribute 'group'
```

If I have set "jsdocs_decorate": false, it just creates new line after ctrl + enter
But if I set it true, then it does the same thing as ctrl+a (highlight everything)
