### ISSUE TITLE
jsdocs_decorate not work

### ISSUE THREAD

**Issue by bigkrp** [spadgos/sublime-jsdocs#395]
when i use Ctrl+Enter sublime.log_commands show me:

```
command: jsdocs_decorate
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "jsdocs in /home/MY_USER/.config/sublime-text-3/Installed Packages/DocBlockr.sublime-package", line 1346, in run
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by eduardoalvara2** [comment]
Neihter to me

I am using Sublime Text 3.0, Build 3143

**Comment by eduardoalvara2** [comment]
Done!, 
I restarted Sublime Text and worked
