### ISSUE TITLE
php7,unsupported variable type array with default value

### ISSUE THREAD

**Issue by itchin** [spadgos/sublime-jsdocs#461]
![qq 20180723113958](https://user-images.githubusercontent.com/11498058/43056209-648cf4b6-8e6d-11e8-8fd3-076856c95200.jpg)
Traceback (most recent call last):
  File "D:\Program Files\Sublime Text-3176\sublime_plugin.py", line 1072, in run_
    return self.run(edit)
  File "D:\Program Files\Sublime Text-3176\Data\Installed Packages\DocBlockr.sublime-package\jsdocs.py", line 163, in run
  File "D:\Program Files\Sublime Text-3176\Data\Installed Packages\DocBlockr.sublime-package\jsdocs.py", line 358, in parse
  File "D:\Program Files\Sublime Text-3176\Data\Installed Packages\DocBlockr.sublime-package\jsdocs.py", line 426, in formatFunction
  File "D:\Program Files\Sublime Text-3176\Data\Installed Packages\DocBlockr.sublime-package\jsdocs.py", line 501, in parseArgs
  File "D:\Program Files\Sublime Text-3176\Data\Installed Packages\DocBlockr.sublime-package\jsdocs.py", line 509, in getArgInfo
  File "D:\Program Files\Sublime Text-3176\Data\Installed Packages\DocBlockr.sublime-package\jsdocs.py", line 798, in getArgType
TypeError: Can't convert 'NoneType' object to str implicitly

**Comment by itchin** [comment]
Only when default value use the short array syntax, which replaces array() with []
